### ISSUE TITLE
This website hemant.codes is dead. 

### ISSUE THREAD

**Issue by Chitrank-dev** [bornmay/Responsive-Portfolio#13]
If it's taking too much time for loading then you should add pre loading screen animation. And fix that eternal loading screen.

**Comment by kaustubhai** [comment]
I don't think that's a valid URL even

**Comment by kaustubhai** [comment]
![Screenshot 2021-01-06 015138](https://user-images.githubusercontent.com/47121025/103694927-bc37fb80-4fc1-11eb-9c0f-d950d58710a8.png)

**Comment by Gulshanaggarwal** [comment]
Yeah,This is not a valid url.I think there is a problem with url.

**Comment by bornmay** [comment]
here: sleepy-engelbart-41ce4b.netlify.app/
